# Name of your site
name: Ninova et al 2023 SUMO GG analysis

# Description of your site (optional)
description: Rmd notebook of MaxQuant GG table data analysis

# The base URL for your site
baseurl: "docs"


# The default layout for your site (optional)
layout: default

# Specify the folder to use for serving your site
# If your site's HTML files are in the "docs" folder, you can specify this as the root folder
# This tells GitPages to serve files from the "docs" folder instead of the root directory
defaults:
  - scope:
      path: "docs"
      type: "html"
    values:
      layout: "default"



